version: '3.8'

services:
  envoy:
    build: ./envoy
    ports:
      - "8080:8080"
    networks:
      - app_network

  nodejs:
    build: ./webserver
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
